### ISSUE TITLE
Slack notification gets truncated

### ISSUE THREAD

**Issue by Atharex** [argoproj-labs/argocd-notifications#101] opened 2020-06-15 16:40 UTC
When trying to display info about a commit message from an Argo CD sync, the displayed message in slack gets truncated at about 60 chars. Of course some messages are longer and would like to be able to also display them fully.

Thought at first this is a limitation of slack attachments, but the same happens when using a text block. 

Both examples below from the notifications CM get truncated prematurely and show ("...") at the end.

```
          attachments: |
            [{
              "title": {{ '"{{' }}.app.metadata.name{{ '}}"' }},
              "title_link": {{ '"{{' }}.context.argoUrl{{ '}}' }}/applications/{{ '{{' }}.app.metadata.name{{ '}}"' }},
              "color": "#18be52",
              "fields": [{
                "title": "Sync Status",
                "value": {{ '"{{' }}.app.status.sync.status{{ '}}"' }},
                "short": true
              }, {
                "title": "Commit Message", 
                "value": {{ '"{{' }} (call .repo.GetCommitMetadata .app.status.sync.revision).Message  {{ '}}"' }},
                "short": false
              }
            ]
            }]
          blocks: |
            [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": {{ '"{{' }} (call .repo.GetCommitMetadata .app.status.sync.revision).Message  {{ '}}"' }}
              }
            }]
```

```
A commit message with a very long body text and multiple expl...
- Sync Status
- Synced
- Commit Message
- A commit message with a very long body text and multiple expl...
```

What can be done to prevent this?

**Comment by notariuss** [comment] 2020-06-17 12:43
Same problem
`{{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}`

**Comment by shawntoffel** [comment] 2020-08-31 21:22
Looks like the message is truncated to 64 characters or the first newline in the reposerver repository.  

https://github.com/argoproj/argo-cd/blob/c49dd8d383a4f6653d2f806acbec8b41b73ed072/reposerver/repository/repository.go#L919

https://github.com/argoproj/argo-cd/blob/fca0f69b5eaa6259ffd551bcf6c986160ec77dc4/pkg/apis/application/v1alpha1/types.go#L711

**Comment by alexmt** [comment] 2021-01-28 20:03
Hello, Thank you for finding the root cause @shawntoffel ! 

The issue was fixed in Argo CD: https://github.com/argoproj/argo-cd/pull/5313 . Message won't be trunkated after upgrading to Argo CD v1.9

**Comment by alexmt** [comment] 2021-01-28 20:04
Closing the issue since there is not much we can do in argocd-notifications

**Closed by alexmt** 2021-01-28 20:04 UTC
